### ISSUE TITLE
cudatoolkit-dev installed within a conda-build requires conda package dependency

### ISSUE THREAD

**Issue by pearu** [conda-forge/cudatoolkit-dev-feedstock#15]
Issue: see the title, otherwise the conda-build fails with
<details>

```
ERROR:conda.core.link:An error occurred while installing package 'conda-forge::cudatoolkit-dev-10.0-2'.
ERROR conda.core.link:_execute(696): An error occurred while installing package 'conda-forge::cudatoolkit-dev-10.0-2'.
Rolling back transaction: ...working... done
Traceback (most recent call last):
  File "/home/pearu/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 2343, in build_tree
    notest=notest,
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1407, in build
    create_build_envs(top_level_pkg, notest)
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 1247, in create_build_envs
    is_conda=m.name() == 'conda')
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda_build/environ.py", line 867, in create_env
    execute_actions(actions, index)
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda/plan.py", line 321, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda/plan.py", line 533, in execute_instructions
    cmd(state, arg)
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda/instructions.py", line 73, in UNLINKLINKTRANSACTION_CMD
    unlink_link_transaction.execute()
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda/core/link.py", line 247, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/home/pearu/miniconda3/lib/python3.7/site-packages/conda/core/link.py", line 712, in _execute
    rollback_excs,
conda.CondaMultiError: post-link script failed for package conda-forge::cudatoolkit-dev-10.0-2
location of failed script: /home/pearu/miniconda3/conda-bld/omniscidb-cuda_1566553013867/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/.cudatoolkit-dev-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Traceback (most recent call last):
  File "/home/pearu/miniconda3/conda-bld/omniscidb-cuda_1566553013867/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/cudatoolkit-dev-post-install.py", line 44, in <module>
    from conda.exports import download, hashsum_file
ModuleNotFoundError: No module named 'conda'

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : base
    active env location : /home/pearu/miniconda3
            shell level : 1
       user config file : /home/pearu/.condarc
 populated config files : /home/pearu/.condarc
          conda version : 4.7.11
    conda-build version : 3.18.9
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : /home/pearu/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/pearu/miniconda3/pkgs
                          /home/pearu/.conda/pkgs
       envs directories : /home/pearu/miniconda3/envs
                          /home/pearu/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Linux/4.15.0-51-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```
</details>

**Comment by andersy005** [comment]
Fixed in #16
