### ISSUE TITLE
Updating cudatoolkit-dev fails: File exists: '/path/to/pkgs/cuda-toolkit'

### ISSUE THREAD

**Issue by pearu** [conda-forge/cudatoolkit-dev-feedstock#18]
Issue:
`conda update -c conda-forge cudatoolkit-dev` fails:
```
...
Running Post installation
downloading https://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_418.87.00_rhel6.run to /home/pearu/mconda3/envs/cudatoolkit-test/pkgs/cudatoolkit-dev/cuda_10.1.243_418.87.00_rhel6.run
Extracting on Linux
Try using /tmp/tmp_yq6alf_/cuda-linux.10.1.243-26907403.run

stderr: Traceback (most recent call last):
  File "/home/pearu/mconda3/envs/cudatoolkit-test/bin/cudatoolkit-dev-post-install.py", line 301, in <module>
    _main()
  File "/home/pearu/mconda3/envs/cudatoolkit-test/bin/cudatoolkit-dev-post-install.py", line 297, in _main
    extractor.extract()
  File "/home/pearu/mconda3/envs/cudatoolkit-test/bin/cudatoolkit-dev-post-install.py", line 168, in extract
    self.copy_files(toolkitpath, self.src_dir)
  File "/home/pearu/mconda3/envs/cudatoolkit-test/bin/cudatoolkit-dev-post-install.py", line 124, in copy_files
    source, destination, symlinks=True, ignore_dangling_symlinks=True
  File "/home/pearu/mconda3/lib/python3.7/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/home/pearu/mconda3/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/pearu/mconda3/envs/cudatoolkit-test/pkgs/cuda-toolkit'

return code: 1

()
```

**Comment by AgrawalAmey** [comment]
Fixed in #35.
