### ISSUE TITLE
Got 'Ensure there is enough space in /tmp and that the installation package is not corrupt' when run 'conda install cudatoolkit-dev -c conda-forge'

### ISSUE THREAD

**Issue by hengfei-wang** [conda-forge/cudatoolkit-dev-feedstock#28]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Got 'Ensure there is enough space in /tmp and that the installation package is not corrupt' when run 'conda install cudatoolkit-dev -c conda-forge'

I think the problem is my tmp directory (2GB available) doesn't have enough space. I want to know how much space installation of cudatoolkit-dev requires and whether I can point another tmp directory to complete the installation. Any idea? 

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /export/local/hxw080/anaconda3/envs/nerfies:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
ca-certificates           2021.1.19            h06a4308_1
certifi                   2020.12.5        py38h06a4308_0
ld_impl_linux-64          2.33.1               h53a641e_7
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libstdcxx-ng              9.1.0                hdf63c60_0
ncurses                   6.2                  he6710b0_1
openssl                   1.1.1j               h27cfd23_0
pip                       21.0.1           py38h06a4308_0
python                    3.8.8                hdb3f193_4
readline                  8.1                  h27cfd23_0
setuptools                52.0.0           py38h06a4308_0
sqlite                    3.35.2               hdfb4753_0
tk                        8.6.10               hbc83047_0
wheel                     0.36.2             pyhd3eb1b0_0
xz                        5.2.5                h7b6447c_0
zlib                      1.2.11               h7b6447c_3

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : nerfies
    active env location : /export/local/hxw080/anaconda3/envs/nerfies
            shell level : 3
       user config file : /home/students/hxw080/.condarc
 populated config files :
          conda version : 4.9.2
    conda-build version : 3.20.5
         python version : 3.8.5.final.0
       virtual packages : __cuda=10.1=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /export/local/hxw080/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /export/local/hxw080/anaconda3/pkgs
                          /home/students/hxw080/.conda/pkgs
       envs directories : /export/local/hxw080/anaconda3/envs
                          /home/students/hxw080/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/3.10.0-1160.11.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 18368:1040
             netrc file : None
           offline mode : False

```
</details>

<br/>
Details about ( <code>conda install</code> ):
<details>

```
$ conda install
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /export/local/hxw080/anaconda3/envs/nerfies

  added / updated specs:
    - cudatoolkit-dev


The following NEW packages will be INSTALLED:

  cudatoolkit-dev    conda-forge/linux-64::cudatoolkit-dev-10.1.243-h516909a_3
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38

The following packages will be UPDATED:

  certifi            pkgs/main::certifi-2020.12.5-py38h06a~ --> conda-forge::certifi-2020.12.5-py38h578d9bd_1

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2021.1.19-~ --> conda-forge::ca-certificates-2020.12.5-ha878542_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: / Extraction failed.
Ensure there is enough space in /tmp and that the installation package is not corrupt
done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'conda-forge::cudatoolkit-dev-10.1.243-h516909a_3'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::cudatoolkit-dev-10.1.243-h516909a_3
location of failed script: /export/local/hxw080/anaconda3/envs/nerfies/bin/.cudatoolkit-dev-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Running Post installation
downloading https://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_418.87.00_rhel6.run to /export/local/hxw080/anaconda3/envs/nerfies/pkgs/cudatoolkit-dev/cuda_10.1.243_418.87.00_rhel6.run
Extracting on Linux

stderr: Signal caught, cleaning up
Traceback (most recent call last):
  File "/export/local/hxw080/anaconda3/envs/nerfies/bin/cudatoolkit-dev-post-install.py", line 273, in <module>
    _main()
  File "/export/local/hxw080/anaconda3/envs/nerfies/bin/cudatoolkit-dev-post-install.py", line 269, in _main
    extractor.extract()
  File "/export/local/hxw080/anaconda3/envs/nerfies/bin/cudatoolkit-dev-post-install.py", line 117, in extract
    status = subprocess.run(cmd, check=True)
  File "/export/local/hxw080/anaconda3/envs/nerfies/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/export/local/hxw080/anaconda3/envs/nerfies/pkgs/cudatoolkit-dev/cuda_10.1.243_418.87.00_rhel6.run', '--extract=/tmp/tmpzzfei42g', '--override']' returned non-zero exit status 15.

return code: 1

()

```
</details>

**Comment by zbarry** [comment]
@hengfei-wang you can redirect the installation tmp dir like so:

`TMPDIR=/your/preferred/path conda install cudatoolkit-dev`

**Comment by hengfei-wang** [comment]
Hi,
Sorry for late response. 
Thank you for your advice. I have changed my computer on which I have the root account. Everything is fine now. I will close the issue.
