### ISSUE TITLE
Segmentation fault on non-root installation

### ISSUE THREAD

**Issue by jnooree** [conda-forge/cudatoolkit-dev-feedstock#44]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: `cudatoolkit-dev` throws segmentation fault then aborts, on non-root installation at post-link step. Full error log is as followings:

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/jnooree/anaconda3/envs/test

  added / updated specs:
    - cudatoolkit-dev=11.1
    - python=3.9


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2021.5.30-ha878542_0
  cudatoolkit-dev    conda-forge/linux-64::cudatoolkit-dev-11.1.1-py39h3811e60_0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.36.1-hea4e1c9_2
  libffi             conda-forge/linux-64::libffi-3.3-h58526e2_2
  libgcc-ng          conda-forge/linux-64::libgcc-ng-11.1.0-hc902ee8_8
  libgomp            conda-forge/linux-64::libgomp-11.1.0-hc902ee8_8
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-11.1.0-h56837e0_8
  ncurses            conda-forge/linux-64::ncurses-6.2-h58526e2_4
  openssl            conda-forge/linux-64::openssl-1.1.1l-h7f98852_0
  pip                conda-forge/noarch::pip-21.2.4-pyhd8ed1ab_0
  python             conda-forge/linux-64::python-3.9.7-h49503c6_0_cpython
  python_abi         conda-forge/linux-64::python_abi-3.9-2_cp39
  readline           conda-forge/linux-64::readline-8.1-h46c0cb4_0
  setuptools         conda-forge/linux-64::setuptools-58.0.3-py39hf3d152e_0
  sqlite             conda-forge/linux-64::sqlite-3.36.0-h9cd32fc_0
  tk                 conda-forge/linux-64::tk-8.6.11-h27826a3_1
  tzdata             conda-forge/noarch::tzdata-2021a-he74cb21_1
  wheel              conda-forge/noarch::wheel-0.37.0-pyhd8ed1ab_1
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1010


Proceed ([y]/n)?

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(699): An error occurred while installing package 'conda-forge::cudatoolkit-dev-11.1.1-py39h3811e60_0'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::cudatoolkit-dev-11.1.1-py39h3811e60_0
location of failed script: /home/jnooree/anaconda3/envs/test/bin/.cudatoolkit-dev-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Log file not open.
Running Post installation
downloading https://developer.download.nvidia.com/compute/cuda/11.1.1/local_installers/cuda_11.1.1_455.32.00_linux.run to /home/jnooree/anaconda3/envs/fgpred/pkgs/cudatoolkit-dev/cuda_11.1.1_455.32.00_linux.run
Extracting on Linux

stderr: Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/home/jnooree/anaconda3/envs/test/bin/cudatoolkit-dev-post-install.py", line 216, in <module>
    _main()
  File "/home/jnooree/anaconda3/envs/test/bin/cudatoolkit-dev-post-install.py", line 212, in _main
    extractor.extract()
  File "/home/jnooree/anaconda3/envs/test/bin/cudatoolkit-dev-post-install.py", line 124, in extract
    subprocess.run(cmd, env=os.environ.copy(), check=True)
  File "/home/jnooree/anaconda3/envs/test/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/jnooree/anaconda3/envs/test/pkgs/cudatoolkit-dev/cuda_11.1.1_455.32.00_linux.run', '--silent', '--toolkit', '--toolkitpath=/tmp/tmp09e_7h5l', '--override']' returned non-zero exit status 139.

return code: 1

()
```

In my other experiment, it succeed with administrator privileges.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
```
Nothing. It was fresh installed via `conda create -c conda-forge -n test python=3.9 cudatoolkit-dev=11.1`
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : None
            shell level : 0
       user config file : /home/jnooree/.condarc
 populated config files : /home/jnooree/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.23=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/jnooree/anaconda3  (writable)
      conda av data dir : /home/jnooree/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jnooree/anaconda3/pkgs
                          /home/jnooree/.conda/pkgs
       envs directories : /home/jnooree/anaconda3/envs
                          /home/jnooree/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Linux/4.4.0-201-generic ubuntu/16.04.7 glibc/2.23
                UID:GID : 1027:500
             netrc file : /home/jnooree/.netrc
           offline mode : False

```
</details>

**Comment by valmar** [comment]
I think that the problem is caused by the cuda installer that the package invokes. It creates a log file in the hardcoded location /tmp/cuda-installer.log

If a user installs the package, and then another users tries to do the same, the segfault will happen because the new user cannot overwrite the previous log file.

I think it works as root because root can overwrite the file. If I manually delete the file as root, the installation works for me. The conda recipe should maybe remove the file after installation.

Please see this forum post about it: https://forums.developer.nvidia.com/t/change-the-path-of-install-log-when-installing-cuda-toolkit/183179/2

**Comment by jnooree** [comment]
Just verified this solution. Thank you very much!

**Comment by andraghetti** [comment]
> I think that the problem is caused by the cuda installer that the package invokes. It creates a log file in the hardcoded location /tmp/cuda-installer.log
> 
> If a user installs the package, and then another users tries to do the same, the segfault will happen because the new user cannot overwrite the previous log file.
> 
> I think it works as root because root can overwrite the file. If I manually delete the file as root, the installation works for me. The conda recipe should maybe remove the file after installation.
> 
> Please see this forum post about it: https://forums.developer.nvidia.com/t/change-the-path-of-install-log-when-installing-cuda-toolkit/183179/2

This removes the possibility to have multiple users installing older versions of cuda (since you fixed it on the most recent ones). Am I wrong?

**Comment by jnooree** [comment]
No, you're right. Maybe a PR backporting this change to the older versions is required.

**Comment by BrandoZhang** [comment]
> No, you're right. Maybe a PR backporting this change to the older versions is required.

It is done?

**Comment by jnooree** [comment]
Sorry for late reply. I tried to backport the changes, but cannot find where to commit. Could you create a new issue to notify the maintainers?

**Comment by tashrifbillah** [comment]
Seconding @valmar : my issue for segmentation fault was that another user tried to install and created `/tmp/cuda-installer.log`. I, being a non-root user, tried to overwrite their log file. Although I had write permission on that file, the issue occurred. After the previous log file was deleted, no more issue. I successfully installed cuda-10.2.
