### ISSUE TITLE
subprocess.CalledProcessError in conda install cudatoolkit-dev=10.1

### ISSUE THREAD

**Issue by pfuerste** [conda-forge/cudatoolkit-dev-feedstock#47]
- [ x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

# packages in environment at /home/fuerste/miniconda3/envs/openmmlab_101:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argcomplete               1.12.3             pyhd3eb1b0_0  
argon2-cffi               20.1.0           py37h27cfd23_1  
async_generator           1.10             py37h28b3542_0  
asynctest                 0.13.0                   pypi_0    pypi
attrs                     21.2.0             pyhd3eb1b0_0  
autopep8                  1.5.7              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
blas                      1.0                         mkl  
bleach                    4.0.0              pyhd3eb1b0_0  
bottleneck                1.3.2            py37heb32a55_1  
brotli                    1.0.9                he6710b0_2  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.9.30            h06a4308_1  
certifi                   2021.10.8        py37h06a4308_0  
cffi                      1.14.6           py37h400218f_0  
charset-normalizer        2.0.7                    pypi_0    pypi
cityscapesscripts         2.2.0                    pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
codecov                   2.1.12                   pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
configparser              5.0.2                    pypi_0    pypi
coverage                  6.0.2                    pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0  
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.24                  pypi_0    pypi
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.4.1            py37h295c915_0  
decorator                 5.1.0              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
docker-pycreds            0.4.0                    pypi_0    pypi
dotty-dict                1.3.0                    pypi_0    pypi
entrypoints               0.3                      py37_0  
expat                     2.4.1                h2531618_2  
ffmpeg                    4.2.2                h20bf706_0  
flake8                    4.0.1                    pypi_0    pypi
flake8-import-order       0.18.1                   pypi_0    pypi
flatbuffers               2.0                      pypi_0    pypi
fontconfig                2.13.1               h6c09931_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.10.4               h5ab3b9f_0  
giflib                    5.2.1                h7b6447c_0  
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.24                   pypi_0    pypi
glib                      2.69.1               h5202010_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
humanfriendly             10.0                     pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      3.3                      pypi_0    pypi
imagecorruptions          1.1.2                    pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        4.2.0                    pypi_0    pypi
importlib_metadata        4.8.1                hd3eb1b0_0  
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2021.3.0          h06a4308_3350  
interrogate               1.5.0                    pypi_0    pypi
ipykernel                 6.4.1            py37h06a4308_1  
ipython                   7.27.0           py37hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.5              pyhd3eb1b0_1  
isort                     4.3.21                   pypi_0    pypi
jedi                      0.18.0           py37h06a4308_1  
jinja2                    3.0.1              pyhd3eb1b0_0  
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0              pyhd3eb1b0_2  
jupyter                   1.0.0            py37h89c1867_6    conda-forge
jupyter_client            7.0.1              pyhd3eb1b0_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.8.1            py37h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
kiwisolver                1.3.2                    pypi_0    pypi
kwarray                   0.5.19                   pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libidn2                   2.3.2                h7f8727e_0  
libopus                   1.3.1                h7b6447c_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.0.3                h7f8727e_2  
libuv                     1.40.0               h7b6447c_0  
libvpx                    1.7.0                h439df22_0  
libwebp                   1.2.0                h89dd481_0  
libwebp-base              1.2.0                h27cfd23_0  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.12               h03d6c58_0  
lz4-c                     1.9.3                h295c915_1  
markupsafe                2.0.1            py37h27cfd23_0  
matplotlib                3.4.3            py37h06a4308_0  
matplotlib-base           3.4.3            py37hbbc1b5f_0  
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4           py37h14c3975_1001  
mkl                       2021.3.0           h06a4308_520  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
mmcls                     0.16.0                   pypi_0    pypi
mmcv-full                 1.3.15                   pypi_0    pypi
mmdet                     2.17.0                   pypi_0    pypi
mmtrack                   0.8.0                    pypi_0    pypi
motmetrics                1.2.0                    pypi_0    pypi
munkres                   1.1.4                      py_0  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.1.0            py37h06a4308_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.6.3                    pypi_0    pypi
ninja                     1.10.2               hff7bd54_1  
notebook                  6.4.5              pyha770c72_0    conda-forge
numexpr                   2.7.3            py37h22e1b3c_1  
numpy                     1.21.2           py37h20f2e39_0  
numpy-base                1.21.2           py37h79a1101_0  
olefile                   0.46                     py37_0  
onnx                      1.7.0                    pypi_0    pypi
onnxruntime               1.9.0                    pypi_0    pypi
opencv-python             4.5.3.56                 pypi_0    pypi
openh264                  2.1.0                hd408876_0  
openssl                   1.1.1l               h7f8727e_0  
ordered-set               4.0.2                    pypi_0    pypi
packaging                 21.0               pyhd3eb1b0_0  
pandas                    1.3.4                    pypi_0    pypi
pandocfilters             1.4.3            py37h06a4308_1  
parso                     0.8.2              pyhd3eb1b0_0  
pathtools                 0.1.2                    pypi_0    pypi
pcre                      8.45                 h295c915_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.4.0            py37h5aabda8_0  
pip                       21.0.1           py37h06a4308_0  
pluggy                    1.0.0                    pypi_0    pypi
prometheus_client         0.11.0             pyhd3eb1b0_0  
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.20             pyhd3eb1b0_0  
prompt_toolkit            3.0.20               hd3eb1b0_0  
protobuf                  3.18.1                   pypi_0    pypi
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2  
py                        1.10.0                   pypi_0    pypi
py-cpuinfo                8.0.0                    pypi_0    pypi
pycocotools               2.0.2                    pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pycparser                 2.20                       py_2  
pyflakes                  2.4.0                    pypi_0    pypi
pygments                  2.10.0             pyhd3eb1b0_0  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py37h05f1152_2  
pyquaternion              0.9.9                    pypi_0    pypi
pyrsistent                0.17.3           py37h7b6447c_0  
pytest                    6.2.5                    pypi_0    pypi
pytest-benchmark          3.4.1                    pypi_0    pypi
python                    3.7.11               h12debd9_0  
python-dateutil           2.8.2              pyhd3eb1b0_0  
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.8.1           py3.7_cuda10.1_cudnn7.6.3_0    pytorch
pytz                      2021.3                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.2.1           py37h295c915_1  
qt                        5.9.7                h5867ecd_1  
qtconsole                 5.1.1              pyhd3eb1b0_0  
qtpy                      1.10.0             pyhd3eb1b0_0  
readline                  8.1                  h27cfd23_0  
requests                  2.26.0                   pypi_0    pypi
scikit-image              0.18.3                   pypi_0    pypi
scikit-learn              1.0                      pypi_0    pypi
scipy                     1.7.1            py37h292c36d_2  
seaborn                   0.11.2             pyhd3eb1b0_0  
send2trash                1.8.0              pyhd3eb1b0_1  
sentry-sdk                1.4.3                    pypi_0    pypi
setuptools                58.0.4           py37h06a4308_0  
setuptools-scm            6.3.2                    pypi_0    pypi
shortuuid                 1.0.1                    pypi_0    pypi
sip                       4.19.8           py37hf484d3e_0  
six                       1.16.0             pyhd3eb1b0_0  
sklearn                   0.0                      pypi_0    pypi
smmap                     5.0.0                    pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0  
subprocess32              3.5.4                    pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.4            py37h06a4308_0  
terminaltables            3.1.0                    pypi_0    pypi
testpath                  0.5.0              pyhd3eb1b0_0  
threadpoolctl             3.0.0                    pypi_0    pypi
tifffile                  2021.10.12               pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
toml                      0.10.2             pyhd3eb1b0_0  
tomli                     1.2.1                    pypi_0    pypi
torchvision               0.9.1                py37_cu101    pytorch
tornado                   6.1              py37h27cfd23_0  
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 5.1.0              pyhd3eb1b0_0  
typing                    3.7.4.3                  pypi_0    pypi
typing_extensions         3.10.0.2           pyh06a4308_0  
ubelt                     0.10.1                   pypi_0    pypi
urllib3                   1.26.7                   pypi_0    pypi
wandb                     0.12.5                   pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1                    py37_1  
wheel                     0.37.0             pyhd3eb1b0_1  
widgetsnbextension        3.5.1                    py37_0  
x264                      1!157.20191217       h7b6447c_0  
xdoctest                  0.15.10                  pypi_0    pypi
xmltodict                 0.12.0                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
yapf                      0.31.0                   pypi_0    pypi
yaspin                    2.1.0                    pypi_0    pypi
zeromq                    4.3.4                h2531618_0  
zipp                      3.6.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0  
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : openmmlab_101
    active env location : /home/fuerste/miniconda3/envs/openmmlab_101
            shell level : 2
       user config file : /home/fuerste/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.4=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/fuerste/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/fuerste/miniconda3/pkgs
                          /home/fuerste/.conda/pkgs
       envs directories : /home/fuerste/miniconda3/envs
                          /home/fuerste/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/5.4.0-89-generic ubuntu/20.04.3 glibc/2.31
                UID:GID : 1071:100
             netrc file : /home/fuerste/.netrc
           offline mode : False
```
</details>

So I am trying to install cudatoolkit-dev 10.1, but it throws the error below. I Cudatoolkit 10.1 was already installed, but I tried to install it anew too. 

```
Downloading and Extracting Packages
cudatoolkit-dev-10.1 | 9 KB      | ####################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'conda-forge::cudatoolkit-dev-10.1.243-h516909a_1'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::cudatoolkit-dev-10.1.243-h516909a_1
location of failed script: /home/fuerste/miniconda3/envs/openmmlab_101/bin/.cudatoolkit-dev-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Running Post installation
re-using previously downloaded /home/fuerste/miniconda3/envs/openmmlab_101/pkgs/cudatoolkit-dev/cuda_10.1.243_418.87.00_rhel6.run

stderr: Traceback (most recent call last):
  File "/home/fuerste/miniconda3/envs/openmmlab_101/bin/cudatoolkit-dev-post-install.py", line 301, in <module>
    _main()
  File "/home/fuerste/miniconda3/envs/openmmlab_101/bin/cudatoolkit-dev-post-install.py", line 294, in _main
    extractor.download_blobs()
  File "/home/fuerste/miniconda3/envs/openmmlab_101/bin/cudatoolkit-dev-post-install.py", line 114, in download_blobs
    self.download(dl_url, dl_path)
  File "/home/fuerste/miniconda3/envs/openmmlab_101/bin/cudatoolkit-dev-post-install.py", line 101, in download
    raise exc
  File "/home/fuerste/miniconda3/envs/openmmlab_101/bin/cudatoolkit-dev-post-install.py", line 99, in download
    subprocess.check_call(cmd)
  File "/home/fuerste/miniconda3/envs/openmmlab_101/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', 'https://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_418.87.00_rhel6.run', '-O', '/home/fuerste/miniconda3/envs/openmmlab_101/pkgs/cudatoolkit-dev/cuda_10.1.243_418.87.00_rhel6.run', '-q']' returned non-zero exit status 3.

return code: 1

()
```

Commands/builds I tried:
`conda install cudatoolkit-dev=10.1 -c conda-forge`
`conda install cudatoolkit=10.1 cudatoolkit-dev=10.1 -c conda-forge`
`conda install cudatoolkit=10.1 cudatoolkit-dev=10.1.243=h516909a_3 -c conda-forge`
`conda install cudatoolkit=10.1 cudatoolkit-dev=10.1.243=h516909a_1 -c conda-forge`
`conda install cudatoolkit=10.1 cudatoolkit-dev=10.1.243=h14c3975_0 -c conda-forge`
The last one throws a different error, see below, the first 4 throw the subprocesserror above.

```Downloading and Extracting Packages
cudatoolkit-dev-10.1 | 9 KB      | ####################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(698): An error occurred while installing package 'conda-forge::cudatoolkit-dev-10.1.243-h14c3975_0'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::cudatoolkit-dev-10.1.243-h14c3975_0
location of failed script: /home/fuerste/miniconda3/envs/openmmlab_101/bin/.cudatoolkit-dev-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: 
return code: 1

()
```
Could you help me fix this?
Edit: Installing in a fresh environment yields the same error.
Edit: Deleted the file at wgets location and reran conda install, fixed it.

**Comment by calebthomas259** [comment]
I had the second error when trying to install cudatoolkit-dev version 11.3.1.

The error message was roughly:
```
LinkError: post-link script failed for package conda-forge::cudatoolkit-dev-11.3.1-py37...
location of failed script: (insert env folder path...)/bin/.cudatoolkit-dev-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout:
stderr: (insert env folder path...)/bin/.cudatoolkit-dev-post-link.sh: line 55: (insert env folder path...)/bin/python: Permission denied
```

Fixed the issue by clearing the packages cache, i.e. `conda clean --packages`
