### ISSUE TITLE
LinkError When Installing cudatoolkit-dev

### ISSUE THREAD

**Issue by oolong936** [conda-forge/cudatoolkit-dev-feedstock#69]
### Comment:

I install cudatoolkit-dev in a Windows environment, but I keep getting connection errors, whether I install with Conda or Mamba
`ERROR conda.core.link:_execute(745): An error occurred while installing package 'conda-forge::cudatoolkit-dev-11.7.0-hab45a8e_5'.
Rolling back transaction: done
class: LinkError
message:
post-link script failed for package conda-forge::cudatoolkit-dev-11.7.0-hab45a8e_5
location of failed script: C:\Users\-\anaconda3\envs\adop_windows\Scripts\.cudatoolkit-dev-post-link.bat`
I haven't found a solution to the problem, please help me.Thanks！！！

**Comment by Taikor-coder** [comment]
I am seeing the same error reported as oolong936 on Windows 11. Appears to be a failure when curl performs a revoke check for the certificates from the download source- Performing the same curl operation in terminal completes with out issue. 

`curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
Traceback (most recent call last):
  File "C:\Users\Admin\miniconda3\envs\textgen\bin\cudatoolkit-dev-post-install.py", line 311, in <module>
    _main()
  File "C:\Users\Admin\miniconda3\envs\textgen\bin\cudatoolkit-dev-post-install.py", line 304, in _main
    extractor.download_blobs()
  File "C:\Users\Admin\miniconda3\envs\textgen\bin\cudatoolkit-dev-post-install.py", line 91, in download_blobs
    self.download(dl_url, dl_path)
  File "C:\Users\Admin\miniconda3\envs\textgen\bin\cudatoolkit-dev-post-install.py", line 168, in download
    raise exc
  File "C:\Users\Admin\miniconda3\envs\textgen\bin\cudatoolkit-dev-post-install.py", line 166, in download
    subprocess.check_call(cmd)
  File "C:\Users\Admin\miniconda3\envs\textgen\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['curl', 'https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_516.01_windows.exe', '-o', 'C:\\Users\\Admin\\miniconda3\\envs\\textgen\\pkgs\\cudatoolkit-dev\\cuda_11.7.0_516.01_windows.exe']' returned non-zero exit status 35.`

Manually downloading the files and putting them in their respective location does not allow the script to complete upon sequential runs. Any ideas?

**Comment by RomStriker** [comment]
I am getting the same error in Windows 11. Using --ssl-no-revoke with curl in the [cudatoolkit-dev-post-install.py]( https://github.com/conda-forge/cudatoolkit-dev-feedstock/blob/ab2938d0e65b0545d88b4febb8c0a55fb1717022/recipe/cudatoolkit-dev-post-install.py#L164) command should skip the revoke check but I am not sure, how to build the conda file after making the change. Any help will be appreciated.

**Comment by RomStriker** [comment]
The issue is the antivirus, turn it off then the error goes away. Reference: https://discourse.julialang.org/t/problem-with-curl-exe-windows-and-package-installation/29525/62

**Comment by AIR-frank** [comment]
I met similar error when conda install  cudatoolkit-dev==11.4.0 in Ubuntu environment


ERROR conda.core.link:_execute(945): An error occurred while installing package 'conda-forge::cudatoolkit-dev-11.4.0-h5764c6d_5'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::cudatoolkit-dev-11.4.0-h5764c6d_5
location of failed script: /home/hjk/anaconda3/envs/simcse/bin/.cudatoolkit-dev-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Running Post installation
re-using previously downloaded /home/hjk/anaconda3/envs/simcse/pkgs/cudatoolkit-dev/cuda_11.4.0_470.42.01_linux.run

stderr: Traceback (most recent call last):
  File "/home/hjk/anaconda3/envs/simcse/bin/cudatoolkit-dev-post-install.py", line 307, in <module>
    _main()
  File "/home/hjk/anaconda3/envs/simcse/bin/cudatoolkit-dev-post-install.py", line 300, in _main
    extractor.download_blobs()
  File "/home/hjk/anaconda3/envs/simcse/bin/cudatoolkit-dev-post-install.py", line 90, in download_blobs
    self.download(dl_url, dl_path)
  File "/home/hjk/anaconda3/envs/simcse/bin/cudatoolkit-dev-post-install.py", line 77, in download
    raise exc
  File "/home/hjk/anaconda3/envs/simcse/bin/cudatoolkit-dev-post-install.py", line 75, in download
    subprocess.check_call(cmd)
  File "/home/hjk/anaconda3/envs/simcse/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wget', 'https://developer.download.nvidia.com/compute/cuda/11.4.0/local_installers/cuda_11.4.0_470.42.01_linux.run', '-O', '/home/hjk/anaconda3/envs/simcse/pkgs/cudatoolkit-dev/cuda_11.4.0_470.42.01_linux.run', '-q']' returned non-zero exit status 4.

return code: 1
