### ISSUE TITLE
Not able to install conda toolkit dev due to Permission Error

### ISSUE THREAD

**Issue by santosh9sanjeev** [conda-forge/cudatoolkit-dev-feedstock#72]
Hi
I wanted to install the cuda-toolkit dev, but it tries to remove the file from the tmp folder(cuda-installer.log) during the installation., which fails due to permission error. I am not the super user and cannot access the tmp folder. Is there any other way for this to work without being the super user?

The error:

ERROR conda.core.link:_execute(740): An error occurred while installing package 'conda-forge::cudatoolkit-dev-11.7.0-h1de0b5d_6'.
Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::cudatoolkit-dev-11.7.0-h1de0b5d_6
location of failed script: /home/santosh.sanjeev/miniconda3/envs/unixmini/bin/.cudatoolkit-dev-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: Running Post installation
re-using previously downloaded /home/santosh.sanjeev/miniconda3/envs/unixmini/pkgs/cudatoolkit-dev/cuda_11.7.0_515.43.04_linux.run

stderr: Traceback (most recent call last):
  File "/home/santosh.sanjeev/miniconda3/envs/unixmini/bin/cudatoolkit-dev-post-install.py", line 118, in extract
    os.remove("/tmp/cuda-installer.log")
PermissionError: [Errno 1] Operation not permitted: '/tmp/cuda-installer.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/santosh.sanjeev/miniconda3/envs/unixmini/bin/cudatoolkit-dev-post-install.py", line 311, in <module>
    _main()
  File "/home/santosh.sanjeev/miniconda3/envs/unixmini/bin/cudatoolkit-dev-post-install.py", line 307, in _main
    extractor.extract()
  File "/home/santosh.sanjeev/miniconda3/envs/unixmini/bin/cudatoolkit-dev-post-install.py", line 120, in extract
    raise RuntimeError(
RuntimeError: Failed to remove /tmp/cuda-installer.log

return code: 1

()

**Comment by yit-b** [comment]
I'm having the same problem. Setting TMPDIR=somewhere/else did not work either. /tmp is hardcoded in the post install script.

**Comment by Kaka23333** [comment]
same problem. Is there any solutions?
