### ISSUE TITLE
cudatoolkit-dev can't be installed on linux conda-forge CI

### ISSUE THREAD

**Issue by artanokhov** [conda-forge/cudatoolkit-dev-feedstock#73]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I'm trying to add cudatoolkit-dev as dependency to get nvcc in conda-forge CI to build OpenVINO plugin that enable deep neural networks inference on NVIDIA GPUs
conda-forge/openvino-feedstock/pull/23

and got following error:
```
023-07-18T15:58:16.1487476Z Rolling back transaction: ...working... ERROR conda.core.link:_execute(740): An error occurred while installing package 'conda-forge::cudatoolkit-dev-11.7.0-h1de0b5d_6'.
2023-07-18T15:58:19.8912931Z done
2023-07-18T15:58:19.9264885Z Traceback (most recent call last):
2023-07-18T15:58:19.9280044Z   File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
2023-07-18T15:58:19.9280750Z     sys.exit(main())
2023-07-18T15:58:19.9326356Z   File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 256, in main
2023-07-18T15:58:19.9327091Z     call_conda_build(action, config)
2023-07-18T15:58:19.9327648Z   File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
2023-07-18T15:58:19.9328026Z     result = api.build(
2023-07-18T15:58:19.9328669Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 253, in build
2023-07-18T15:58:19.9329268Z     return build_tree(
2023-07-18T15:58:19.9337988Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3799, in build_tree
2023-07-18T15:58:19.9339142Z     packages_from_this = build(
2023-07-18T15:58:19.9339974Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2572, in build
2023-07-18T15:58:19.9340451Z     create_build_envs(top_level_pkg, notest)
2023-07-18T15:58:19.9341093Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2412, in create_build_envs
2023-07-18T15:58:19.9341566Z     environ.create_env(
2023-07-18T15:58:19.9342132Z   File "/opt/conda/lib/python3.10/site-packages/conda_build/environ.py", line 1058, in create_env
2023-07-18T15:58:19.9345448Z     execute_actions(actions, index)
2023-07-18T15:58:19.9346131Z   File "/opt/conda/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
2023-07-18T15:58:19.9348777Z     return f(*args, **kwds)
2023-07-18T15:58:19.9349448Z   File "/opt/conda/lib/python3.10/site-packages/conda/plan.py", line 322, in execute_actions
2023-07-18T15:58:19.9368003Z     execute_instructions(plan, index, verbose)
2023-07-18T15:58:19.9368912Z   File "/opt/conda/lib/python3.10/site-packages/conda/plan.py", line 532, in execute_instructions
2023-07-18T15:58:19.9369406Z     cmd(state, arg)
2023-07-18T15:58:19.9370004Z   File "/opt/conda/lib/python3.10/site-packages/conda/instructions.py", line 73, in UNLINKLINKTRANSACTION_CMD
2023-07-18T15:58:19.9375100Z     unlink_link_transaction.execute()
2023-07-18T15:58:19.9375885Z   File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 283, in execute
2023-07-18T15:58:19.9376406Z     self._execute(tuple(chain(*chain(*zip(*self.prefix_action_groups.values())))))
2023-07-18T15:58:19.9377031Z   File "/opt/conda/lib/python3.10/site-packages/conda/core/link.py", line 756, in _execute
2023-07-18T15:58:19.9385554Z     raise CondaMultiError(
2023-07-18T15:58:19.9386366Z conda.CondaMultiError: post-link script failed for package conda-forge::cudatoolkit-dev-11.7.0-h1de0b5d_6
2023-07-18T15:58:19.9387251Z location of failed script: /home/conda/feedstock_root/build_artifacts/openvino_1689695384762/_build_env/bin/.cudatoolkit-dev-post-link.sh
2023-07-18T15:58:19.9387771Z ==> script messages <==
2023-07-18T15:58:19.9388112Z <None>
2023-07-18T15:58:19.9388466Z ==> script output <==
2023-07-18T15:58:19.9388820Z stdout: Running Post installation
2023-07-18T15:58:19.9389775Z downloading https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_515.43.04_linux.run to /home/conda/feedstock_root/build_artifacts/openvino_1689695384762/_build_env/pkgs/cudatoolkit-dev/cuda_11.7.0_515.43.04_linux.run
2023-07-18T15:58:19.9390413Z Extracting on Linux
2023-07-18T15:58:19.9390663Z 
2023-07-18T15:58:19.9391611Z stderr: /home/conda/feedstock_root/build_artifacts/openvino_1689695384762/_build_env/bin/cudatoolkit-dev-post-install.py:45: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
2023-07-18T15:58:19.9392307Z   from distutils.dir_util import copy_tree
2023-07-18T15:58:19.9392900Z terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
2023-07-18T15:58:19.9393726Z   what():  boost::filesystem::copy_file: No space left on device: "./builds/nsight_systems/host-linux-x64/libQt5Qml.so.5", "/tmp/tmpfg_ekz50/nsight-systems-2022.1.3/host-linux-x64/libQt5Qml.so.5"
2023-07-18T15:58:19.9394763Z /home/conda/feedstock_root/build_artifacts/openvino_1689695384762/_build_env/pkgs/cudatoolkit-dev/cuda_11.7.0_515.43.04_linux.run: line 533:   655 Aborted                 (core dumped) ./cuda-installer --silent --toolkit --toolkitpath=/tmp/tmpfg_ekz50 --override
2023-07-18T15:58:19.9395383Z Traceback (most recent call last):
2023-07-18T15:58:19.9396016Z   File "/home/conda/feedstock_root/build_artifacts/openvino_1689695384762/_build_env/bin/cudatoolkit-dev-post-install.py", line 311, in <module>
2023-07-18T15:58:19.9396509Z     _main()
2023-07-18T15:58:19.9397110Z   File "/home/conda/feedstock_root/build_artifacts/openvino_1689695384762/_build_env/bin/cudatoolkit-dev-post-install.py", line 307, in _main
2023-07-18T15:58:19.9397942Z     extractor.extract()
2023-07-18T15:58:19.9398608Z   File "/home/conda/feedstock_root/build_artifacts/openvino_1689695384762/_build_env/bin/cudatoolkit-dev-post-install.py", line 135, in extract
2023-07-18T15:58:19.9399274Z     subprocess.run(cmd, env=os.environ.copy(), check=True)
2023-07-18T15:58:19.9399765Z   File "/home/conda/feedstock_root/build_artifacts/openvino_1689695384762/_build_env/lib/python3.11/subprocess.py", line 571, in run
2023-07-18T15:58:19.9400212Z     raise CalledProcessError(retcode, process.args,
2023-07-18T15:58:19.9401115Z subprocess.CalledProcessError: Command '['/home/conda/feedstock_root/build_artifacts/openvino_1689695384762/_build_env/pkgs/cudatoolkit-dev/cuda_11.7.0_515.43.04_linux.run', '--silent', '--toolkit', '--toolkitpath=/tmp/tmpfg_ekz50', '--override']' returned non-zero exit status 134.
2023-07-18T15:58:19.9401637Z 
2023-07-18T15:58:19.9401956Z return code: 1
2023-07-18T15:58:19.9402193Z 
2023-07-18T15:58:19.9402510Z ()
```

Full log available by link
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/746870/logs/33

### Installed packages

```shell
2023-07-18T15:54:20.2386103Z The following NEW packages will be INSTALLED:
2023-07-18T15:54:20.2386402Z 
2023-07-18T15:54:20.2387121Z     _libgcc_mutex:                        0.1-conda_forge           conda-forge
2023-07-18T15:54:20.2387686Z     _openmp_mutex:                        4.5-2_gnu                 conda-forge
2023-07-18T15:54:20.2388254Z     _sysroot_linux-64_curr_repodata_hack: 3-h69a702a_13             conda-forge
2023-07-18T15:54:20.2388806Z     binutils_impl_linux-64:               2.40-hf600244_0           conda-forge
2023-07-18T15:54:20.2389367Z     binutils_linux-64:                    2.40-hbdbef99_0           conda-forge
2023-07-18T15:54:20.2389889Z     bzip2:                                1.0.8-h7f98852_4          conda-forge
2023-07-18T15:54:20.2390546Z     c-ares:                               1.19.1-hd590300_0         conda-forge
2023-07-18T15:54:20.2391139Z     ca-certificates:                      2023.5.7-hbcca054_0       conda-forge
2023-07-18T15:54:20.2391686Z     cmake:                                3.26.4-hcfe8598_0         conda-forge
2023-07-18T15:54:20.2392243Z     cudatoolkit-dev:                      11.7.0-h1de0b5d_6         conda-forge
2023-07-18T15:54:20.2392784Z     curl:                                 8.1.2-hca28451_1          conda-forge
2023-07-18T15:54:20.2393335Z     expat:                                2.5.0-hcb278e6_1          conda-forge
2023-07-18T15:54:20.2394725Z     flatbuffers:                          23.3.3-hcb278e6_1         conda-forge
2023-07-18T15:54:20.2396788Z     gcc_impl_linux-64:                    12.3.0-he2b93b0_0         conda-forge
2023-07-18T15:54:20.2397595Z     gcc_linux-64:                         12.3.0-h76fc315_0         conda-forge
2023-07-18T15:54:20.2398533Z     gettext:                              0.21.1-h27087fc_0         conda-forge
2023-07-18T15:54:20.2399312Z     git:                                  2.41.0-pl5321h86e50cf_0   conda-forge
2023-07-18T15:54:20.2399878Z     gxx_impl_linux-64:                    12.3.0-he2b93b0_0         conda-forge
2023-07-18T15:54:20.2400452Z     gxx_linux-64:                         12.3.0-h8a814eb_0         conda-forge
2023-07-18T15:54:20.2401035Z     kernel-headers_linux-64:              3.10.0-h4a8ded7_13        conda-forge
2023-07-18T15:54:20.2401589Z     keyutils:                             1.6.1-h166bdaf_0          conda-forge
2023-07-18T15:54:20.2402138Z     krb5:                                 1.21.1-h659d440_0         conda-forge
2023-07-18T15:54:20.2402682Z     ld_impl_linux-64:                     2.40-h41732ed_0           conda-forge
2023-07-18T15:54:20.2403238Z     libcurl:                              8.1.2-hca28451_1          conda-forge
2023-07-18T15:54:20.2403787Z     libedit:                              3.1.20191231-he28a2e2_2   conda-forge
2023-07-18T15:54:20.2404320Z     libev:                                4.33-h516909a_1           conda-forge
2023-07-18T15:54:20.2404883Z     libexpat:                             2.5.0-hcb278e6_1          conda-forge
2023-07-18T15:54:20.2405416Z     libffi:                               3.4.2-h7f98852_5          conda-forge
2023-07-18T15:54:20.2406451Z     libgcc-devel_linux-64:                12.3.0-h8bca6fd_0         conda-forge
2023-07-18T15:54:20.2407238Z     libgcc-ng:                            13.1.0-he5830b7_0         conda-forge
2023-07-18T15:54:20.2407839Z     libgomp:                              13.1.0-he5830b7_0         conda-forge
2023-07-18T15:54:20.2408397Z     libiconv:                             1.17-h166bdaf_0           conda-forge
2023-07-18T15:54:20.2408931Z     libidn2:                              2.3.4-h166bdaf_0          conda-forge
2023-07-18T15:54:20.2409645Z     libnghttp2:                           1.52.0-h61bc06f_0         conda-forge
2023-07-18T15:54:20.2410170Z     libnsl:                               2.0.0-h7f98852_0          conda-forge
2023-07-18T15:54:20.2411341Z     libprotobuf:                          3.20.3-h3eb15da_0         conda-forge
2023-07-18T15:54:20.2411893Z     libsanitizer:                         12.3.0-h0f45ef3_0         conda-forge
2023-07-18T15:54:20.2412423Z     libsqlite:                            3.42.0-h2797004_0         conda-forge
2023-07-18T15:54:20.2412964Z     libssh2:                              1.11.0-h0841786_0         conda-forge
2023-07-18T15:54:20.2413493Z     libstdcxx-devel_linux-64:             12.3.0-h8bca6fd_0         conda-forge
2023-07-18T15:54:20.2414046Z     libstdcxx-ng:                         13.1.0-hfd8a6a1_0         conda-forge
2023-07-18T15:54:20.2414585Z     libunistring:                         0.9.10-h7f98852_0         conda-forge
2023-07-18T15:54:20.2415099Z     libuuid:                              2.38.1-h0b41bf4_0         conda-forge
2023-07-18T15:54:20.2415627Z     libuv:                                1.44.2-h166bdaf_0         conda-forge
2023-07-18T15:54:20.2416157Z     libzlib:                              1.2.13-hd590300_5         conda-forge
2023-07-18T15:54:20.2416697Z     ncurses:                              6.4-hcb278e6_0            conda-forge
2023-07-18T15:54:20.2417412Z     ninja:                                1.11.1-h924138e_0         conda-forge
2023-07-18T15:54:20.2418047Z     openssl:                              3.1.1-hd590300_1          conda-forge
2023-07-18T15:54:20.2418588Z     pcre2:                                10.40-hc3806b6_0          conda-forge
2023-07-18T15:54:20.2419111Z     perl:                                 5.32.1-4_hd590300_perl5   conda-forge
2023-07-18T15:54:20.2419651Z     pkg-config:                           0.29.2-h36c2ea0_1008      conda-forge
2023-07-18T15:54:20.2420180Z     python:                               3.11.4-hab00c5b_0_cpython conda-forge
2023-07-18T15:54:20.2420722Z     readline:                             8.2-h8228510_1            conda-forge
2023-07-18T15:54:20.2421290Z     rhash:                                1.4.3-h166bdaf_0          conda-forge
2023-07-18T15:54:20.2421831Z     sysroot_linux-64:                     2.17-h4a8ded7_13          conda-forge
2023-07-18T15:54:20.2422370Z     tk:                                   8.6.12-h27826a3_0         conda-forge
2023-07-18T15:54:20.2422883Z     tzdata:                               2023c-h71feb2d_0          conda-forge
2023-07-18T15:54:20.2423537Z     wget:                                 1.20.3-ha35d2d1_1         conda-forge
2023-07-18T15:54:20.2424050Z     xz:                                   5.2.6-h166bdaf_0          conda-forge
2023-07-18T15:54:20.2424585Z     zlib:                                 1.2.13-hd590300_5         conda-forge
2023-07-18T15:54:20.2425109Z     zstd:                                 1.5.2-hfc55251_7          conda-forge
```

### Environment info

```shell
conda-forge CI

user-agent : conda/23.3.1 requests/2.31.0 CPython/3.10.12 Linux/5.15.0-1041-azure centos/7.9.2009 glibc/2.17
```

**Comment by artanokhov** [comment]
Seems not the case, because you can directly specify 
```
- {{ compiler('cuda') }}
```
in conda-forge recipe.
Closing this bug
